import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NavMenu } from "@/components/NavMenu/NavMenu";
import { AuthProvider } from "@/providers/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <AuthProvider>
    <html lang="en">
      <body className={inter.className}>
        <NavMenu />
        {children}
      </body>
    </html>
  </AuthProvider>
);

export default RootLayout;
